// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZVNtINqtLvaLWoIxuSR8iZJk0OrNV324',
    appId: '1:1071680529670:web:1842c2386788668da72a87',
    messagingSenderId: '1071680529670',
    projectId: 'teachsync-3e5d9',
    authDomain: 'teachsync-3e5d9.firebaseapp.com',
    storageBucket: 'teachsync-3e5d9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDt8_pqkUbeAXJKgHxQ3XpC9npRB8n65Nw',
    appId: '1:1071680529670:android:17039d5e0c7380fea72a87',
    messagingSenderId: '1071680529670',
    projectId: 'teachsync-3e5d9',
    storageBucket: 'teachsync-3e5d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzJXJX0U1tSfypxZ9VstzNgzk5pLXHPuo',
    appId: '1:1071680529670:ios:fd8414c59a4fb8aca72a87',
    messagingSenderId: '1071680529670',
    projectId: 'teachsync-3e5d9',
    storageBucket: 'teachsync-3e5d9.firebasestorage.app',
    iosBundleId: 'com.example.vteachsync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzJXJX0U1tSfypxZ9VstzNgzk5pLXHPuo',
    appId: '1:1071680529670:ios:fd8414c59a4fb8aca72a87',
    messagingSenderId: '1071680529670',
    projectId: 'teachsync-3e5d9',
    storageBucket: 'teachsync-3e5d9.firebasestorage.app',
    iosBundleId: 'com.example.vteachsync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZVNtINqtLvaLWoIxuSR8iZJk0OrNV324',
    appId: '1:1071680529670:web:520bda68d2102389a72a87',
    messagingSenderId: '1071680529670',
    projectId: 'teachsync-3e5d9',
    authDomain: 'teachsync-3e5d9.firebaseapp.com',
    storageBucket: 'teachsync-3e5d9.firebasestorage.app',
  );
}
